#!/usr/bin/env python3
"""Fetch FRESH real daily Google Trends for the demo hero shows, through today.

The gold `local_interest` (and `fact_trends_daily`) stop ~2026-06-15 because the daily
Trends collector stalled on 429s, leaving the demo chart's Trends line sparse and trailing
off mid-window. Rather than fabricate values (the project's standing rule = **no synthetic
data**), this pulls the *real* daily interest-over-time for each hero's artist+metro **now**,
in a single per-(artist, geo) pull so the 0-100 series stays internally consistent (the scale
is per-pull; never splice two pulls). Output is a committed, provenance-stamped artifact the
web chart overlays for the hero shows.

Heroes are taken from the same selection the dropdown uses (`hero_candidates.select_heroes`),
so this stays in lockstep with `web/src/data/heroShows.ts`.

Deterministic + re-runnable (the only nondeterminism is Google's live data + rate limiting,
both stamped). No LLM. Run in the `music-demand` env (pytrends + pandas pinned):

    /opt/anaconda3/envs/music-demand/bin/python eda/backfill_hero_trends.py --limit 1 --dry-run
    /opt/anaconda3/envs/music-demand/bin/python eda/backfill_hero_trends.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "eda"))
sys.path.insert(0, str(REPO_ROOT / "google_trends_api"))

import hero_candidates as hc  # noqa: E402
from _common import DEFAULT_DATASET, DEFAULT_PROJECT, utc_now_iso  # noqa: E402
from trends_client import TrendsClient  # noqa: E402

WEB_HERO_TRENDS_TS = REPO_ROOT / "web" / "src" / "data" / "heroTrends.ts"
DEFAULT_TIMEFRAME = "today 3-m"  # ~90 days, returns DAILY granularity through today


def get_heroes(project: str, dataset: str) -> list[dict]:
    """The exact dropdown hero set (same selection as heroShows.ts)."""
    records = hc.rank(hc.classify(hc.load_candidates(project, dataset)))
    return hc.select_heroes(records)


def geo_for(rec: dict) -> str | None:
    """Google Trends geo (US-<STATE>-<DMA>) for a hero's show metro."""
    state = (rec.get("state_code") or "").strip()
    dma = str(rec.get("dma_code") or "").strip()
    if not state or not dma:
        return None
    return f"US-{state}-{dma}"


def fetch_hero_trends(client: TrendsClient, rec: dict, timeframe: str) -> list[dict]:
    """One per-(artist, geo) daily pull -> [{date, interest, is_partial}, ...]."""
    query = (rec.get("artist_name") or rec.get("event_name") or "").strip()
    geo = geo_for(rec)
    if not query or not geo:
        return []
    frame = client.interest_over_time(query, geo, timeframe=timeframe)
    if frame is None or frame.empty or query not in frame.columns:
        return []
    partial = frame["isPartial"] if "isPartial" in frame.columns else None
    out = []
    for i, (idx, value) in enumerate(frame[query].items()):
        out.append({
            "date": idx.strftime("%Y-%m-%d"),
            "interest": int(value),
            "is_partial": bool(partial.iloc[i]) if partial is not None else False,
        })
    return out


def write_ts(hero_series: dict[str, dict], path: Path, as_of: str, timeframe: str) -> Path:
    """Emit the committed artifact the web chart overlays (real daily Trends per hero)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by eda/backfill_hero_trends.py — do not edit by hand.",
        "// REAL daily Google Trends interest, pulled live per (artist, metro). The 0-100 scale",
        "// is per-pull (comparable across time for one show, never across shows). Re-run the",
        f"// script to refresh. Timeframe={timeframe!r}. As of {as_of}.",
        "",
        "export type HeroTrendPoint = { date: string; interest: number; is_partial: boolean };",
        "",
        "export const HERO_TRENDS: Record<string, HeroTrendPoint[]> = ",
        json.dumps(hero_series, ensure_ascii=False, indent=2),
        ";",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=DEFAULT_PROJECT)
    parser.add_argument("--dataset", default=DEFAULT_DATASET)
    parser.add_argument("--timeframe", default=DEFAULT_TIMEFRAME)
    parser.add_argument("--out", default=str(WEB_HERO_TRENDS_TS))
    parser.add_argument("--limit", type=int, default=0, help="Fetch only the first N heroes (0 = all).")
    parser.add_argument("--min-interval", type=float, default=20.0, help="Seconds between calls (rate cap).")
    parser.add_argument("--dry-run", action="store_true", help="Fetch + print coverage; write nothing.")
    parser.add_argument("--query", help="Diagnostic: fetch this exact query (skips hero selection).")
    parser.add_argument("--geo", help="Diagnostic: geo for --query, e.g. US or US-CA-807.")
    args = parser.parse_args()

    if args.query is not None:
        client = TrendsClient(min_interval=args.min_interval)
        frame = client.interest_over_time(args.query, args.geo or "US", timeframe=args.timeframe)
        empty = frame is None or frame.empty
        print(f"[diag] '{args.query}' @ {args.geo or 'US'} [{args.timeframe}]: "
              f"{'EMPTY' if empty else f'{len(frame)} rows, cols={list(frame.columns)}'}")
        if not empty:
            print(frame.tail(8).to_string())
        return 0

    heroes = get_heroes(args.project, args.dataset)
    if args.limit:
        heroes = heroes[: args.limit]
    client = TrendsClient(min_interval=args.min_interval)

    series: dict[str, dict] = {}
    for rec in heroes:
        geo = geo_for(rec)
        name = rec.get("artist_name") or rec.get("event_name")
        try:
            points = fetch_hero_trends(client, rec, args.timeframe)
        except Exception as exc:  # noqa: BLE001 - one act failing must not lose the rest
            print(f"[backfill] {name:<26} @ {geo}: FAILED ({exc})")
            continue
        nonzero = sum(1 for p in points if p["interest"] > 0)
        last = points[-1]["date"] if points else "—"
        print(f"[backfill] {name:<26} @ {geo}: {len(points)} daily pts "
              f"({nonzero} nonzero, latest {last})")
        if points:
            series[rec["event_id"]] = points

    if args.dry_run:
        print(f"[backfill] dry run — fetched {len(series)} hero series, wrote nothing.")
        return 0

    out = write_ts(series, Path(args.out), utc_now_iso(), args.timeframe)
    print(f"[backfill] wrote {len(series)} hero trend series -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
