#!/usr/bin/env python3
"""Find upcoming shows with real signal variability — the good live demos.

Two deterministic ranked lists over the honest gold star (no synthetic data):

  1. price movers — upcoming shows whose OBSERVED price_min actually changed
     (>= 2 distinct values), ranked by swing %. These make the price-history
     chart interesting; ~96% of shows are flat, so they must be hunted.
  2. local-vs-global divergence — upcoming shows where worldwide popularity
     (latest YouTube subscribers) and local search interest disagree:
     "global heavyweight, locally quiet" and "local heat, small global
     footprint". These make the two popularity signals visibly independent —
     the project's core thesis on one chart.

Output: eda/output/demo_variability.md (committed). Re-run any time:

    python eda/demo_variability.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "eda"))
from _common import DEFAULT_DATASET, DEFAULT_PROJECT, bq_rows, utc_now_iso  # noqa: E402

OUT_PATH = REPO_ROOT / "eda" / "output" / "demo_variability.md"

PRICE_MOVERS_SQL = """
WITH per_event AS (
  SELECT event_id, ANY_VALUE(artist_id) AS artist_id,
         COUNT(DISTINCT price_min) AS distinct_prices,
         COUNTIF(price_min IS NOT NULL) AS priced_days,
         MIN(price_min) AS lo, MAX(price_min) AS hi
  FROM `{p}.{d}.fact_event_demand`
  WHERE price_min IS NOT NULL
  GROUP BY event_id
  HAVING COUNT(DISTINCT price_min) >= 2
)
SELECT pe.event_id, a.artist_name, e.event_name, v.venue_name, v.city,
       CAST(e.show_date AS STRING) AS show_date, pe.priced_days,
       pe.lo, pe.hi, ROUND(SAFE_DIVIDE(pe.hi - pe.lo, pe.lo) * 100, 1) AS swing_pct
FROM per_event pe
JOIN `{p}.{d}.dim_event` e ON e.event_id = pe.event_id
JOIN `{p}.{d}.dim_venue` v ON v.venue_id = e.venue_id
LEFT JOIN `{p}.{d}.dim_artist` a ON a.artist_id = pe.artist_id
WHERE e.show_date >= CURRENT_DATE()
ORDER BY swing_pct DESC, pe.event_id
LIMIT 15
"""

DIVERGENCE_SQL = """
WITH per_event AS (
  SELECT event_id, ANY_VALUE(artist_id) AS artist_id,
         AVG(local_interest) AS avg_interest
  FROM `{p}.{d}.fact_event_demand`
  WHERE snapshot_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
  GROUP BY event_id
  HAVING AVG(local_interest) IS NOT NULL
),
latest_subs AS (
  SELECT artist_id, official_subscribers
  FROM `{p}.{d}.fact_youtube`
  QUALIFY ROW_NUMBER() OVER (PARTITION BY artist_id ORDER BY snapshot_date DESC) = 1
)
SELECT pe.event_id, a.artist_name, e.event_name, v.venue_name, v.city,
       CAST(e.show_date AS STRING) AS show_date,
       s.official_subscribers AS subs, ROUND(pe.avg_interest, 1) AS avg_local_interest,
       CASE WHEN s.official_subscribers >= 1000000 AND pe.avg_interest < 25
              THEN 'global heavyweight, locally quiet'
            WHEN s.official_subscribers < 100000 AND pe.avg_interest >= 60
              THEN 'local heat, small global footprint'
       END AS divergence
FROM per_event pe
JOIN latest_subs s ON s.artist_id = pe.artist_id
JOIN `{p}.{d}.dim_event` e ON e.event_id = pe.event_id
JOIN `{p}.{d}.dim_venue` v ON v.venue_id = e.venue_id
LEFT JOIN `{p}.{d}.dim_artist` a ON a.artist_id = pe.artist_id
WHERE e.show_date >= CURRENT_DATE()
  AND (
    (s.official_subscribers >= 1000000 AND pe.avg_interest < 25)
    OR (s.official_subscribers < 100000 AND pe.avg_interest >= 60)
  )
ORDER BY divergence, s.official_subscribers DESC, pe.event_id
LIMIT 20
"""


def _table(rows: list[dict], columns: list[str]) -> list[str]:
    if not rows:
        return ["_no qualifying shows right now_", ""]
    lines = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    lines += ["| " + " | ".join(str(r.get(c, "")) for c in columns) + " |" for r in rows]
    return lines + [""]


def main() -> None:
    project, dataset = DEFAULT_PROJECT, DEFAULT_DATASET
    movers = bq_rows(PRICE_MOVERS_SQL.format(p=project, d=dataset), project)
    divergent = bq_rows(DIVERGENCE_SQL.format(p=project, d=dataset), project)

    lines = [
        "# Demo variability — upcoming shows worth showing live",
        "",
        f"Generated by `eda/demo_variability.py` on {utc_now_iso()} (honest star only, "
        "no synthetic data). Click any `event_id` into the dashboard search or an "
        "agent answer to see the chart.",
        "",
        "## Price movers (observed price actually changed)",
        "",
        *_table(
            movers,
            ["event_id", "artist_name", "venue_name", "city", "show_date",
             "priced_days", "lo", "hi", "swing_pct"],
        ),
        "## Local-vs-global divergence (the project thesis, visible on one chart)",
        "",
        *_table(
            divergent,
            ["event_id", "artist_name", "venue_name", "city", "show_date",
             "subs", "avg_local_interest", "divergence"],
        ),
    ]
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[demo_variability] {len(movers)} movers, {len(divergent)} divergent -> {OUT_PATH}")


if __name__ == "__main__":
    main()
