// Generated by eda/hero_candidates.py — do not edit by hand.
// Re-run `python eda/hero_candidates.py` to refresh from the live forecast.
// Curated demo heroes: credible (flat/rising/falling) forecasts, one per artist,
// ranked by YouTube subscribers. As of 2026-06-29T06:23:21+00:00.

export const HERO_EVENT_IDS: string[] = [
  "rZ7HnEZ1AfeFOV", // Air Supply — flat, 2,110,000 subs
  "rZ7HnEZ1Afvp-f", // Bone Thugs-N-Harmony — flat, 2,100,000 subs
  "rZ7HnEZ1AfPZxK", // 6LACK — flat, 2,020,000 subs
  "rZ7HnEZ1Af0y7K", // TX2 — rising, 1,150,000 subs
  "rZ7HnEZ1Af09vd", // Masego — flat, 993,000 subs
  "rZ7HnEZ1Af0Z4K", // Madeon — flat, 904,000 subs
  "rZ7HnEZ1AfP6oN", // Rolling Quartz — falling, 821,000 subs
  "rZ7HnEZ1Afr4PN", // Blue October — falling, 617,000 subs
  "rZ7HnEZ1Af-pbS", // The Wallflowers — rising, 291,000 subs
  "rZ7HnEZ1AfPfFd", // CAIN — flat, 273,000 subs
  "rZ7HnEZ1Afk9oV", // Marcus King Band — rising, 189,000 subs
  "rZ7HnEZ1AfPUed", // Underoath — rising, 169,000 subs
];

export const DEFAULT_HERO_EVENT_ID = "rZ7HnEZ1Af0Z4K";
