// Generated by eda/hero_candidates.py — do not edit by hand.
// Re-run `python eda/hero_candidates.py` to refresh from the live forecast.
// Pre-cached demo heroes: credible (flat/rising/falling) forecasts, one per artist,
// ranked by 3-source signal richness (Trends + YouTube days). The dropdown renders
// from this with no /shows fetch. As of 2026-06-29T07:01:07+00:00.

import type { ShowSummary } from "../types";

export const HERO_SHOWS: ShowSummary[] = [
  {"event_id": "rZ7HnEZ1Af-pbS", "event_name": "The Wallflowers, The Whitmore Sisters", "artist_name": "The Wallflowers", "venue_name": "Belly Up", "city": "Solana Beach", "state_code": "CA", "show_date": "2026-10-08", "status_code": "", "price_min": 77.55, "price_max": 132.25, "local_interest": null, "yt_subscribers": 291000.0, "yt_views": null, "forecast_price": 85.91824585918428}, // The Wallflowers: rising, 5 trends + 11 youtube days
  {"event_id": "rZ7HnEZ1AfPJGN", "event_name": "Bingo Loco", "artist_name": "Bingo Loco", "venue_name": "San Jose Improv", "city": "San Jose", "state_code": "CA", "show_date": "2026-09-04", "status_code": "", "price_min": 37.17, "price_max": 107.72, "local_interest": null, "yt_subscribers": 2280.0, "yt_views": null, "forecast_price": 45.76703670240567}, // Bingo Loco: rising, 10 trends + 14 youtube days
  {"event_id": "rZ7HnEZ1Afk9oV", "event_name": "ATOMIC HABITZ: Chris Dave X Marcus King X Cleo \"Pookie\" Sample X DJ Ginyard", "artist_name": "Marcus King Band", "venue_name": "Blue Note Jazz Club", "city": "New York", "state_code": "NY", "show_date": "2026-07-30", "status_code": "", "price_min": 77.65, "price_max": 88.98, "local_interest": null, "yt_subscribers": 189000.0, "yt_views": null, "forecast_price": 87.14209180709352}, // Marcus King Band: rising, 6 trends + 12 youtube days
  {"event_id": "rZ7HnEZ1Afrp4N", "event_name": "Hatebreed: SUMMER SLAUGHTER TOUR 2026", "artist_name": "Hatebreed", "venue_name": "Pop's Concert Venue", "city": "Sauget", "state_code": "IL", "show_date": "2026-07-21", "status_code": "", "price_min": 40.57, "price_max": 79.19, "local_interest": null, "yt_subscribers": 161000.0, "yt_views": null, "forecast_price": 48.66446639545196}, // Hatebreed: rising, 5 trends + 11 youtube days
  {"event_id": "rZ7HnEZ1AfjMbd", "event_name": "Shakey Graves - Fondness, Etc. Tour", "artist_name": "Shakey Graves", "venue_name": "The Hall", "city": "Little Rock", "state_code": "AR", "show_date": "2026-06-17", "status_code": "", "price_min": 47.1, "price_max": 81.14, "local_interest": null, "yt_subscribers": 67600.0, "yt_views": null, "forecast_price": 47.1}, // Shakey Graves: flat, 4 trends + 14 youtube days
  {"event_id": "rZ7HnEZ1Af_O8S", "event_name": "Cameron Whitcomb, Dylan Conrique", "artist_name": "Cameron Whitcomb", "venue_name": "Bottom Lounge", "city": "Chicago", "state_code": "IL", "show_date": "2026-07-31", "status_code": "", "price_min": 46.81, "price_max": 46.81, "local_interest": null, "yt_subscribers": 157000.0, "yt_views": null, "forecast_price": 48.121635494704385}, // Cameron Whitcomb: flat, 4 trends + 11 youtube days
  {"event_id": "rZ7HnEZ1AfjAvd", "event_name": "Evanston Folk Festival 2026 (2-Day Pass)", "artist_name": "Trampled By Turtles", "venue_name": "Dawes Park ", "city": "Evanston", "state_code": "IL", "show_date": "2026-09-12", "status_code": "", "price_min": 154.37, "price_max": 489.03, "local_interest": null, "yt_subscribers": 60900.0, "yt_views": null, "forecast_price": 170.78177828280803}, // Trampled By Turtles: rising, 4 trends + 10 youtube days
  {"event_id": "rZ7HnEZ1Af-P_K", "event_name": "Turnover, Narrow Head, She's Green", "artist_name": "Turnover", "venue_name": "The Ritz", "city": "San Jose", "state_code": "CA", "show_date": "2026-07-04", "status_code": "", "price_min": 263.35, "price_max": 520.85, "local_interest": null, "yt_subscribers": 24000.0, "yt_views": null, "forecast_price": 239.21577957913863}, // Turnover: falling, 4 trends + 5 youtube days
  {"event_id": "rZ7HnEZ1Af00jd", "event_name": "Everclear with American Hi-Fi", "artist_name": "Everclear", "venue_name": "The Independent", "city": "San Francisco", "state_code": "CA", "show_date": "2026-10-24", "status_code": "", "price_min": 136.05, "price_max": 236.05, "local_interest": null, "yt_subscribers": 113000.0, "yt_views": null, "forecast_price": 102.29202601319408}, // Everclear: falling, 8 trends + 14 youtube days
];

export const HERO_EVENT_IDS: string[] = HERO_SHOWS.map((show) => show.event_id);

export const DEFAULT_HERO_EVENT_ID = "rZ7HnEZ1Af-pbS";
