"""Resolve a Ticketmaster venue to a Google Trends DMA + geo code.

Loads two committed reference tables (generated by build_dma_table.py and
build_zip_dma_table.py):

  - ``reference/dma_geo.csv``     DMA -> ``US-<STATE>-<DMA>`` geo code, name, state
  - ``reference/zip_to_dma.csv``  ZIP -> DMA number (~41k ZIPs, all 210 DMAs)

Resolution is ZIP-first (Ticketmaster venue ZIP coverage is ~100%), with a
state-dominant-DMA fallback when a ZIP is missing or unknown. A lat/lon
point-in-polygon path is the documented upgrade if ZIP coverage ever drops (see
build_zip_dma_table.py) — not needed at current coverage.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

REFERENCE = Path(__file__).with_name("reference")
DMA_GEO = REFERENCE / "dma_geo.csv"
ZIP_TO_DMA = REFERENCE / "zip_to_dma.csv"


@dataclass(frozen=True)
class DmaHit:
    """One resolved metro: DMA number, Trends geo code, name, and how we got it."""

    dma: str            # Nielsen DMA number, e.g. "807"
    geo_code: str       # Google Trends geo code, e.g. "US-CA-807"
    dma_name: str       # e.g. "San Francisco-Oakland-San Jose CA"
    state: str          # canonical state prefix, e.g. "CA"
    method: str         # "zip" | "state" — provenance of the match


class GeoLookup:
    """In-memory venue -> DMA resolver backed by the two committed CSVs."""

    def __init__(self, dma_geo: Path = DMA_GEO, zip_to_dma: Path = ZIP_TO_DMA) -> None:
        # dma -> (geo_code, dma_name, state)
        self._dma: dict[str, tuple[str, str, str]] = {}
        with dma_geo.open(encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                self._dma[row["dma"]] = (row["geo_code"], row["dma_name"], row["state"])

        # zip -> dma
        self._zip: dict[str, str] = {}
        with zip_to_dma.open(encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                self._zip[row["zip"]] = row["dma"]

        # state -> dominant DMA (the in-state DMA covering the most ZIPs), for the
        # rare venue with a missing/unknown ZIP.
        state_dma_counts: dict[str, dict[str, int]] = {}
        for zip_code, dma in self._zip.items():
            state = self._dma.get(dma, (None, None, None))[2]
            if state:
                state_dma_counts.setdefault(state, {}).setdefault(dma, 0)
                state_dma_counts[state][dma] += 1
        self._state_dma: dict[str, str] = {
            state: max(counts, key=counts.get) for state, counts in state_dma_counts.items()
        }

    @staticmethod
    def _norm_zip(zip_code: str | None) -> str | None:
        if not zip_code:
            return None
        # Ticketmaster ZIPs are sometimes ZIP+4 ("94102-1234") or short; take 5.
        digits = "".join(c for c in str(zip_code) if c.isdigit())
        return digits[:5].zfill(5) if digits else None

    def _hit(self, dma: str, method: str) -> DmaHit | None:
        info = self._dma.get(dma)
        if not info:
            return None
        geo_code, dma_name, state = info
        return DmaHit(dma=dma, geo_code=geo_code, dma_name=dma_name, state=state, method=method)

    def resolve(self, *, zip_code: str | None = None, state: str | None = None) -> DmaHit | None:
        """Resolve a venue to its DMA. ZIP first, then the state's dominant DMA."""

        norm = self._norm_zip(zip_code)
        if norm and norm in self._zip:
            return self._hit(self._zip[norm], "zip")
        if state and (dma := self._state_dma.get(state.strip().upper())):
            return self._hit(dma, "state")
        return None
