import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { fetchShow } from "./api/client";
import { AskPanel } from "./components/AskPanel";
import { DemandSignalsChart } from "./components/DemandSignalsChart";
import { SearchPanel } from "./components/SearchPanel";

// The docs view pulls in react-markdown + mermaid; lazy-load it so the default
// dashboard bundle stays lean.
const DocsPanel = lazy(() => import("./components/DocsPanel"));
import { DEFAULT_HERO_EVENT_ID, HERO_SHOWS } from "./data/heroShows";
import type { ShowDetail, ShowSummary } from "./types";
import { formatDate } from "./utils/formatters";
import { scrollToPageTop } from "./utils/scroll";

type LoadState = "idle" | "loading" | "success" | "error";

// The dropdown is a pre-cached, curated set of heroes (credible forecast + consistent
// Trends/YouTube coverage), generated by eda/hero_candidates.py. Rendering from this avoids
// fetching the full ~40k-event /shows payload; only the selected show is fetched live.
const INITIAL_SELECTED_ID =
  HERO_SHOWS.find((show) => show.event_id === DEFAULT_HERO_EVENT_ID)?.event_id ??
  HERO_SHOWS[0]?.event_id ??
  "";

function isAbortError(error: unknown): boolean {
  return error instanceof DOMException && error.name === "AbortError";
}

function formatShowOption(show: ShowSummary): string {
  return `${show.artist_name || show.event_name} at ${show.venue_name}`;
}

type View = "dashboard" | "ask" | "docs";

function App() {
  const [view, setView] = useState<View>("dashboard");
  const [shows] = useState<ShowSummary[]>(HERO_SHOWS);
  const [searchPick, setSearchPick] = useState<ShowSummary | null>(null);
  const [selectedId, setSelectedId] = useState(INITIAL_SELECTED_ID);
  const [selectedShow, setSelectedShow] = useState<ShowDetail | null>(null);
  const [showState, setShowState] = useState<LoadState>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!selectedId) {
      setSelectedShow(null);
      setShowState("idle");
      return;
    }

    const controller = new AbortController();

    setShowState("loading");
    setErrorMessage(null);

    fetchShow(selectedId, controller.signal)
      .then((show) => {
        if (controller.signal.aborted) {
          return;
        }

        setSelectedShow(show);
        setShowState("success");
      })
      .catch((error: unknown) => {
        if (isAbortError(error) || controller.signal.aborted) {
          return;
        }

        setSelectedShow(null);
        setShowState("error");
        setErrorMessage("Could not load the selected show. Try another show or restart the API.");
      });

    return () => controller.abort();
  }, [selectedId]);

  // Ask-result rows carry only an event_id: select it (the effect above fetches
  // /show/{id}) and make sure the dashboard view is the one showing. The rows sit
  // below the chart (embedded panel) or on another view, so scroll the dashboard
  // back into sight; search picks stay put because their results render above the
  // chart and the updated view appears right below the clicked row.
  const openShowById = (eventId: string) => {
    setSelectedId(eventId);
    setView("dashboard");
    scrollToPageTop();
  };

  // Search picks join the dropdown so a non-hero show selected from the search
  // results still renders as the current selection. Ask-result picks arrive as a
  // bare id, so the loaded detail joins the dropdown once it exists.
  const dropdownShows = useMemo(() => {
    const extras: ShowSummary[] = [];
    if (searchPick && !shows.some((show) => show.event_id === searchPick.event_id)) {
      extras.push(searchPick);
    }
    if (
      selectedShow &&
      !shows.some((show) => show.event_id === selectedShow.event_id) &&
      !extras.some((show) => show.event_id === selectedShow.event_id)
    ) {
      extras.push(selectedShow);
    }
    return extras.length > 0 ? [...shows, ...extras] : shows;
  }, [shows, searchPick, selectedShow]);

  const selectedSummary = useMemo(
    () => dropdownShows.find((show) => show.event_id === selectedId) ?? null,
    [selectedId, dropdownShows],
  );
  const summaryShow = selectedShow ?? selectedSummary;
  const isLoadingSelectedShow = showState === "loading" && !selectedShow;

  return (
    <main className="app-shell">
      <header className="app-header">
        <div>
          <p className="eyebrow">Team Shakshuka</p>
          <h1>Live Music Demand Dashboard</h1>
          <p className="header-copy">
            Compare ticket movement, local interest, artist attention, and forecast signals for
            curated live music events.
          </p>
        </div>
        <div className="header-controls">
          <nav className="view-toggle" aria-label="View">
            <button
              type="button"
              className={view === "dashboard" ? "is-active" : ""}
              onClick={() => setView("dashboard")}
            >
              Dashboard
            </button>
            <button
              type="button"
              className={view === "ask" ? "is-active" : ""}
              onClick={() => setView("ask")}
            >
              Ask the music warehouse
            </button>
            <button
              type="button"
              className={view === "docs" ? "is-active" : ""}
              onClick={() => setView("docs")}
            >
              How it works
            </button>
          </nav>
          {view === "dashboard" && (
            <label className="show-picker">
              <span>Demo show</span>
              <select
                value={selectedId}
                onChange={(event) => setSelectedId(event.target.value)}
                aria-label="Demo show"
                disabled={shows.length === 0}
              >
                {dropdownShows.length === 0 && <option value="">No shows available</option>}
                {dropdownShows.map((show) => (
                  <option key={show.event_id} value={show.event_id}>
                    {formatShowOption(show)}
                  </option>
                ))}
              </select>
            </label>
          )}
        </div>
      </header>

      {view === "ask" && <AskPanel onOpenShow={openShowById} />}

      {view === "docs" && (
        <Suspense
          fallback={
            <section className="status-panel" aria-live="polite">
              <strong>Loading documentation view</strong>
              <p>Fetching the markdown and diagram renderers…</p>
            </section>
          }
        >
          <DocsPanel />
        </Suspense>
      )}

      {view === "dashboard" && (
        <>
          <SearchPanel
            onPick={(show) => {
              setSearchPick(show);
              setSelectedId(show.event_id);
            }}
          />

      {errorMessage && (
        <section className="status-panel is-error" role="alert">
          <strong>Live API issue</strong>
          <p>{errorMessage}</p>
        </section>
      )}

      {summaryShow && (
        <section className="summary-band" aria-label="Selected show summary">
          <div>
            <p className="eyebrow">Selected show</p>
            <h2>{summaryShow.event_name}</h2>
            <p>
              {summaryShow.venue_name} · {summaryShow.city}, {summaryShow.state_code} ·{" "}
              {formatDate(summaryShow.show_date)}
            </p>
          </div>
        </section>
      )}

      {isLoadingSelectedShow && (
        <section className="status-panel" aria-live="polite">
          <strong>Loading selected show</strong>
          <p>Fetching history and forecast rows from /show/event_id.</p>
        </section>
      )}

          {selectedShow && <DemandSignalsChart show={selectedShow} />}

          {/* Same panel as the dedicated view (shared component), embedded so a
              viewer can ask questions in context without switching views. */}
          <AskPanel compact onOpenShow={openShowById} />
        </>
      )}
    </main>
  );
}

export default App;
