import { useEffect, useMemo, useState } from "react";
import { fetchShow } from "./api/client";
import { DemandSignalsChart } from "./components/DemandSignalsChart";
import { MetricCard } from "./components/MetricCard";
import { DEFAULT_HERO_EVENT_ID, HERO_SHOWS } from "./data/heroShows";
import type { ShowDetail, ShowSummary } from "./types";
import { formatDate, formatMoney, formatNumber } from "./utils/formatters";

type LoadState = "idle" | "loading" | "success" | "error";

// The dropdown is a pre-cached, curated set of heroes (credible forecast + consistent
// Trends/YouTube coverage), generated by eda/hero_candidates.py. Rendering from this avoids
// fetching the full ~40k-event /shows payload; only the selected show is fetched live.
const INITIAL_SELECTED_ID =
  HERO_SHOWS.find((show) => show.event_id === DEFAULT_HERO_EVENT_ID)?.event_id ??
  HERO_SHOWS[0]?.event_id ??
  "";

function isAbortError(error: unknown): boolean {
  return error instanceof DOMException && error.name === "AbortError";
}

function formatShowOption(show: ShowSummary): string {
  return `${show.artist_name || show.event_name} at ${show.venue_name}`;
}

function App() {
  const [shows] = useState<ShowSummary[]>(HERO_SHOWS);
  const [selectedId, setSelectedId] = useState(INITIAL_SELECTED_ID);
  const [selectedShow, setSelectedShow] = useState<ShowDetail | null>(null);
  const [showState, setShowState] = useState<LoadState>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!selectedId) {
      setSelectedShow(null);
      setShowState("idle");
      return;
    }

    const controller = new AbortController();

    setShowState("loading");
    setErrorMessage(null);

    fetchShow(selectedId, controller.signal)
      .then((show) => {
        if (controller.signal.aborted) {
          return;
        }

        setSelectedShow(show);
        setShowState("success");
      })
      .catch((error: unknown) => {
        if (isAbortError(error) || controller.signal.aborted) {
          return;
        }

        setSelectedShow(null);
        setShowState("error");
        setErrorMessage("Could not load the selected show. Try another show or restart the API.");
      });

    return () => controller.abort();
  }, [selectedId]);

  const selectedSummary = useMemo(
    () => shows.find((show) => show.event_id === selectedId) ?? null,
    [selectedId, shows],
  );
  const summaryShow = selectedShow ?? selectedSummary;
  const isLoadingSelectedShow = showState === "loading" && !selectedShow;

  return (
    <main className="app-shell">
      <header className="app-header">
        <div>
          <p className="eyebrow">Team Shakshuka</p>
          <h1>Live Music Demand Dashboard</h1>
          <p className="header-copy">
            Compare ticket movement, local interest, artist attention, and forecast signals for
            curated live music events.
          </p>
        </div>
        <label className="show-picker">
          <span>Demo show</span>
          <select
            value={selectedId}
            onChange={(event) => setSelectedId(event.target.value)}
            aria-label="Demo show"
            disabled={shows.length === 0}
          >
            {shows.length === 0 && <option value="">No shows available</option>}
            {shows.map((show) => (
              <option key={show.event_id} value={show.event_id}>
                {formatShowOption(show)}
              </option>
            ))}
          </select>
        </label>
      </header>

      {errorMessage && (
        <section className="status-panel is-error" role="alert">
          <strong>Live API issue</strong>
          <p>{errorMessage}</p>
        </section>
      )}

      {summaryShow && (
        <section className="summary-band" aria-label="Selected show summary">
          <div>
            <p className="eyebrow">Selected show</p>
            <h2>{summaryShow.event_name}</h2>
            <p>
              {summaryShow.venue_name} · {summaryShow.city}, {summaryShow.state_code} ·{" "}
              {formatDate(summaryShow.show_date)}
            </p>
          </div>
          <div className="metric-row">
            <MetricCard
              label="Price range"
              value={`${formatMoney(summaryShow.price_min)} - ${formatMoney(summaryShow.price_max)}`}
            />
            <MetricCard label="Local interest" value={formatNumber(summaryShow.local_interest)} />
            <MetricCard label="YouTube views" value={formatNumber(summaryShow.yt_views)} />
            <MetricCard label="Forecast lowest price" value={formatMoney(summaryShow.forecast_price)} />
          </div>
        </section>
      )}

      {isLoadingSelectedShow && (
        <section className="status-panel" aria-live="polite">
          <strong>Loading selected show</strong>
          <p>Fetching history and forecast rows from /show/event_id.</p>
        </section>
      )}

      {selectedShow && <DemandSignalsChart show={selectedShow} />}
    </main>
  );
}

export default App;
